# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locationv1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='locationv1.proto',
  package='locationservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10locationv1.proto\x12\x0flocationservice\"\x1b\n\x08location\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"7\n\x0emap_coordinate\x12\x11\n\tlattitude\x18\x01 \x01(\x02\x12\x12\n\nlongtitude\x18\x02 \x01(\x02\x32\x64\n\x10location_service\x12P\n\x10\x63onvert_location\x12\x19.locationservice.location\x1a\x1f.locationservice.map_coordinate\"\x00\x62\x06proto3')
)




_LOCATION = _descriptor.Descriptor(
  name='location',
  full_name='locationservice.location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='locationservice.location.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=64,
)


_MAP_COORDINATE = _descriptor.Descriptor(
  name='map_coordinate',
  full_name='locationservice.map_coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lattitude', full_name='locationservice.map_coordinate.lattitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longtitude', full_name='locationservice.map_coordinate.longtitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['location'] = _LOCATION
DESCRIPTOR.message_types_by_name['map_coordinate'] = _MAP_COORDINATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

location = _reflection.GeneratedProtocolMessageType('location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'locationv1_pb2'
  # @@protoc_insertion_point(class_scope:locationservice.location)
  ))
_sym_db.RegisterMessage(location)

map_coordinate = _reflection.GeneratedProtocolMessageType('map_coordinate', (_message.Message,), dict(
  DESCRIPTOR = _MAP_COORDINATE,
  __module__ = 'locationv1_pb2'
  # @@protoc_insertion_point(class_scope:locationservice.map_coordinate)
  ))
_sym_db.RegisterMessage(map_coordinate)



_LOCATION_SERVICE = _descriptor.ServiceDescriptor(
  name='location_service',
  full_name='locationservice.location_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='convert_location',
    full_name='locationservice.location_service.convert_location',
    index=0,
    containing_service=None,
    input_type=_LOCATION,
    output_type=_MAP_COORDINATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATION_SERVICE)

DESCRIPTOR.services_by_name['location_service'] = _LOCATION_SERVICE

# @@protoc_insertion_point(module_scope)
