/*
 * Swagger propertiestore
 *
 * This is a sample propertiestore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Property struct {

	Id int64 `json:"id,omitempty"`

	ListingID int64 `json:"ListingID"`

	Address *Address `json:"Address"`

	PhotoUrls []interface{} `json:"photoUrls,omitempty"`

	Tags []Tag `json:"tags,omitempty"`

	// property status in database
	Status string `json:"status,omitempty"`
}
