/*
 * Swagger propertiestore
 *
 * This is a sample propertiestore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"//",
		Index,
	},

	Route{
		"Addproperty",
		strings.ToUpper("Post"),
		"//property",
		Addproperty,
	},

	Route{
		"Deleteproperty",
		strings.ToUpper("Delete"),
		"//property/{propertyID}",
		Deleteproperty,
	},

	Route{
		"FindpropertiesByLocation",
		strings.ToUpper("Get"),
		"//property/findByLocation",
		FindpropertiesByLocation,
	},

	Route{
		"GetpropertyById",
		strings.ToUpper("Get"),
		"//property/{propertyID}",
		GetpropertyById,
	},

	Route{
		"UpdatepropertyWithForm",
		strings.ToUpper("Put"),
		"//property/{propertyID}",
		UpdatepropertyWithForm,
	},

	Route{
		"UploadFile",
		strings.ToUpper("Post"),
		"//property/{propertyID}/uploadImage",
		UploadFile,
	},
}
